// Task spec §8: "Run the differential test against vfr-screen.mp4 too -- variable durations are
// where stts run-length expansion breaks." That fixture lives in fixtures/ (gitignored, locally
// generated by scripts/make-fixtures.sh -- see .gitignore), so it isn't present in a fresh clone
// or in this worktree. Skip gracefully rather than failing the suite when it's absent; run it for
// real on a machine that has fixtures/ populated.

import { existsSync, readFileSync } from 'node:fs';
import path from 'node:path';
import { ALL_FORMATS, CustomSource, EncodedPacketSink, Input } from 'mediabunny';
import { describe, expect, it } from 'vitest';
import { buildMp4Index } from '../../spikes/A-remux/mp4-index';
import { buildIndex } from './build-index';
import { BufferByteSource } from './sources/buffer-byte-source';
import { localTicksToPresentationSeconds } from './time';

const FIXTURE_PATH = path.join(__dirname, '..', '..', '..', 'fixtures', 'vfr-screen.mp4');

// describe.skipIf's callback still runs at collection time even when skipped, so the
// gitignored-and-often-absent fixture must not be read unconditionally -- guard with a plain
// `if` instead, and register nothing at all (rather than a skipped suite) when it's missing.
if (existsSync(FIXTURE_PATH)) {
  registerVfrDifferentialSuite();
} else {
  describe.skip('differential: vfr-screen.mp4 (skipped -- fixtures/vfr-screen.mp4 not present locally)', () => {
    it('skipped', () => undefined);
  });
}

function registerVfrDifferentialSuite(): void {
  const bytes = readFileSync(FIXTURE_PATH);
  const uint8 = new Uint8Array(bytes.buffer, bytes.byteOffset, bytes.byteLength);

  describe('differential: vfr-screen.mp4 (variable-duration stts expansion)', () => {
    it('agrees with the spike parser on every sample field', async () => {
    const ours = await buildIndex(new BufferByteSource(uint8));
    expect(ours.ok).toBe(true);
    if (!ours.ok) return;

    const spike = await buildMp4Index(new File([uint8], 'vfr-screen.mp4'));
    for (const ourTrack of ours.tracks) {
      if (ourTrack.kind === 'other') continue;
      const spikeTrack = spike.tracks.find((t) => t.trackId === ourTrack.trackId);
      expect(spikeTrack).toBeDefined();
      if (!spikeTrack) continue;

      const disagreements: string[] = [];
      if (ourTrack.sampleCount !== spikeTrack.sampleCount) disagreements.push(`sampleCount: ours=${String(ourTrack.sampleCount)} spike=${String(spikeTrack.sampleCount)}`);
      const n = Math.min(ourTrack.sampleCount, spikeTrack.sampleCount);
      for (let i = 0; i < n; i += 1) {
        if (ourTrack.dts[i] !== spikeTrack.dts[i]) disagreements.push(`dts[${String(i)}]: ours=${String(ourTrack.dts[i])} spike=${String(spikeTrack.dts[i])}`);
        if (ourTrack.pts[i] !== spikeTrack.cts[i]) disagreements.push(`pts[${String(i)}]: ours=${String(ourTrack.pts[i])} spike=${String(spikeTrack.cts[i])}`);
      }
      if (disagreements.length > 0) console.warn(`track ${String(ourTrack.trackId)}:\n${disagreements.slice(0, 20).join('\n')}`);
      expect(disagreements).toEqual([]);
    }
  });

  it('agrees with mediabunny on every sample timestamp (edit-list-adjusted)', async () => {
    const ours = await buildIndex(new BufferByteSource(uint8));
    expect(ours.ok).toBe(true);
    if (!ours.ok) return;

    const input = new Input({ source: new CustomSource({ getSize: () => uint8.byteLength, read: (s, e) => uint8.subarray(s, e) }), formats: ALL_FORMATS });
    const mbTracks = await input.getTracks();

    for (const ourTrack of ours.tracks) {
      if (ourTrack.kind === 'other') continue;
      const mbTrack = mbTracks.find((t) => t.id === ourTrack.trackId);
      expect(mbTrack).toBeDefined();
      if (!mbTrack) continue;
      const sink = new EncodedPacketSink(mbTrack);

      const disagreements: string[] = [];
      let i = 0;
      for await (const packet of sink.packets(undefined, undefined, { metadataOnly: true })) {
        if (i >= ourTrack.sampleCount) break;
        const oursTs = localTicksToPresentationSeconds(ourTrack.pts[i], ourTrack.timescale, ourTrack.editOffsetTicks);
        if (Math.abs(oursTs - packet.timestamp) > 1e-6) disagreements.push(`timestamp[${String(i)}]: ours=${String(oursTs)} mediabunny=${String(packet.timestamp)}`);
        i += 1;
      }
      if (disagreements.length > 0) console.warn(`track ${String(ourTrack.trackId)}:\n${disagreements.slice(0, 20).join('\n')}`);
      expect(disagreements).toEqual([]);
    }
  });
  });
}
